### ISSUE TITLE
Monday API changes - V 2023-10

### ISSUE THREAD

**Issue by saurabhm19781** [clintmasden/monday.client.v2#11]
Hello,
We are using this monday client to interact with Monday.com. As per article and migration plan: https://developer.monday.com/api-reference/docs/migrating-to-v-2023-10 ... Looks like there are some breaking changes. We are wondering if you will be providing a new version with these changes?

Thanks & Regards

**Comment by clintmasden** [comment]
No, i will not.  If you provide a PR, with any other requirements, then i'll accept and deploy a new version.
