### ISSUE TITLE
Enable package for .NET Framework.

### ISSUE THREAD

**Issue by Zweitze** [clintmasden/monday.client.v2#2]
Some of us cannot convert to .NET Standard for all kinds of reasons.
It is possible to convert by starting a new project, importing sources files and figuring out the dependencies, plus one compiler error - but then it's much easier to miss updates in this library.

The wish is having a package targeting multiple .NET platforms. Some reading on the subject:
https://weblog.west-wind.com/posts/2017/Jun/22/MultiTargeting-and-Porting-a-NET-Library-to-NET-Core-20

**Comment by clintmasden** [comment]
You are welcome to submit a pull request and or fork the repo with the changes you are seeking. I'll review the changes/source and we'll go from there.

**Comment by Zweitze** [comment]
I looked into creating a pull request with multiple targets - but rebuilding the repo in VS2017 appears to be impossible: It requires .NET Core 3.1 SDK, which can only be built with VS 2019. Migrating to VS2019 is currently not possible on my system.

For reference to others in this situation, the following changes were required:
1. Package GraphQL.Client needs an update to version 3.2.2
2. Package GraphQL.Client.Serializer.Newtonsoft is now required, version 3.2.2
3. Package Newtonsoft.Json is required, minimum version 12.0.3
4. The minimum .NET Framework version is 4.7.2, because one of the dependencies require System.Reactive, which requires this version.
5. Source file MondayClient.cs needs to be changed:

Add:
```
using GraphQL.Client.Serializer.Newtonsoft;
```
Change constructor MondayClient(), member _graphQlHttpClient is constructed with an extra parameter:
```
public MondayClient(string apiKey)
{
    _graphQlHttpClient = new GraphQLHttpClient("https://api.monday.com/v2/",  new NewtonsoftJsonSerializer());
    _graphQlHttpClient.HttpClient.DefaultRequestHeaders.Authorization = AuthenticationHeaderValue.Parse(apiKey);
}
```
