### ISSUE TITLE
User.CreatedAt should be nullable

### ISSUE THREAD

**Issue by Zweitze** [clintmasden/monday.client.v2#3]
My Monday-setup has a user with an empty field created_at. As a result, MondayClient.GetUsers() and MondayClient.GetUser() fail.

I am not sure why Monday does not return a field created_at, so I can't really help reproducing.
The one outstanding attribute is that this user is a pending user - currently no other users have an empty created_at, and no other users are pending. This could be the correlation.

**Comment by clintmasden** [comment]
Confirm with your setup/data that by adjusting the User object, Created At property to the below resolves the issue. 

```
User.cs
public DateTime? CreatedAt { get; set; }
```

On confirmation, I'll update the repo/package.

**Comment by Zweitze** [comment]
Yes, when I change User.cs to:

>         /// <summary>
>         ///     The user's creation date.
>         /// </summary>
>         [JsonProperty("created_at")]
>         public DateTime? CreatedAt { get; set; }
> 

The problem goes away and I get a user with CreatedAt==null.

**Comment by clintmasden** [comment]
committed / updated nuget package, on any further issues/requests/enhancements, please all create a pull request!
